Repository betagouv/anssi-nis2, pull requests merged in 2024-06, with the labels that each got.

#148 [Éligibilité en CSV] Nouvelle règle « Secteurs »
  anssi-nis2-ui/src/questionnaire/specifications/FabriqueDeSpecifications.ts
  anssi-nis2-ui/src/questionnaire/specifications/FormatDesSpecificationsCSV.ts
  anssi-nis2-ui/src/questionnaire/specifications/regles/RegleSecteurs.ts
  anssi-nis2-ui/src/questionnaire/specifications/specifications-completes.csv
  anssi-nis2-ui/test/questionnaire/specifications/FabriqueDeSpecifications.spec.ts
  anssi-nis2-ui/test/questionnaire/specifications/csv/specification-ose-est-regulee-ee.csv
  anssi-nis2-ui/test/questionnaire/specifications/csv/specification-une-ligne.csv
Labels: enhancement

#149 Spécifie explicitement le séparateur du CSV
  anssi-nis2-ui/src/questionnaire/specifications/LecteurDeSpecifications.ts
  anssi-nis2-ui/src/questionnaire/specifications/specifications-completes.csv
  anssi-nis2-ui/test/questionnaire/specifications/csv/specification-ose-est-regulee-ee.csv
  anssi-nis2-ui/test/questionnaire/specifications/csv/specification-une-ligne.csv
Labels: enhancement

#150 [Éligibilité en CSV] Nouvelle règle « Sous-secteurs »
  anssi-nis2-ui/src/questionnaire/specifications/FabriqueDeSpecifications.ts
  anssi-nis2-ui/src/questionnaire/specifications/FormatDesSpecificationsCSV.ts
  anssi-nis2-ui/src/questionnaire/specifications/regles/RegleSousSecteurs.ts
  anssi-nis2-ui/src/questionnaire/specifications/specifications-completes.csv
  anssi-nis2-ui/test/questionnaire/specifications/FabriqueDeSpecifications.spec.ts
  anssi-nis2-ui/test/questionnaire/specifications/csv/specification-ose-est-regulee-ee.csv
  anssi-nis2-ui/test/questionnaire/specifications/csv/specification-une-ligne.csv
Labels: enhancement

#151 Ajoute un lien vers la FAQ
  anssi-nis2-ui/src/App.scss
  anssi-nis2-ui/src/Components/MenuDesktop.tsx
  anssi-nis2-ui/src/Components/MenuMobile.tsx
Labels: Front

#152 Ajustements Front
  anssi-nis2-ui/src/Accueil.tsx
  anssi-nis2-ui/src/Components/Accueil/BandeauEnSavoirPlus.tsx
  anssi-nis2-ui/src/Components/Accueil/BandeauNis2EU.tsx
  anssi-nis2-ui/src/Components/Accueil/BandeauObligations.tsx
  anssi-nis2-ui/src/Components/Accueil/BandeauQuandSePreparer.tsx
  anssi-nis2-ui/src/Components/Accueil/ElementObligation.tsx
  anssi-nis2-ui/src/Components/Accueil/LogoUnionEuropeenneNIS2.tsx
  anssi-nis2-ui/src/Components/Accueil/index.ts
  anssi-nis2-ui/src/Components/FormRestezInformes.tsx
  anssi-nis2-ui/src/Directive.tsx
Labels: Front

#153 Mise à disposition de la plaquette PDF de NIS 2
  anssi-nis2-api/src/main.ts
  anssi-nis2-api/statique/Plaquette_NIS2_2024.pdf
  anssi-nis2-ui/src/Directive.tsx
Labels: enhancement

#154 [Éligibilité en CSV] Début de la nouvelle règle « Activités »
  anssi-nis2-ui/src/References/LibellesActivites.ts
  anssi-nis2-ui/src/questionnaire/specifications/FabriqueDeSpecifications.ts
  anssi-nis2-ui/src/questionnaire/specifications/FormatDesSpecificationsCSV.ts
  anssi-nis2-ui/src/questionnaire/specifications/regles/RegleActivites.ts
  anssi-nis2-ui/src/questionnaire/specifications/specifications-completes.csv
  anssi-nis2-ui/test/questionnaire/specifications/FabriqueDeSpecifications.spec.ts
  anssi-nis2-ui/test/questionnaire/specifications/csv/specification-ose-est-regulee-ee.csv
  anssi-nis2-ui/test/questionnaire/specifications/csv/specification-une-ligne.csv
Labels: enhancement

#155 [Éligibilité en CSV] Termine la règle « Activités »
  anssi-nis2-ui/src/questionnaire/specifications/regles/RegleActivites.ts
  anssi-nis2-ui/test/questionnaire/specifications/FabriqueDeSpecifications.spec.ts
  anssi-nis2-ui/test/questionnaire/specifications/casDeTests.activites.ts
Labels: enhancement

#156 [Éligibilité en CSV] Termine la règle « Extra - Fourniture de service »
  anssi-nis2-ui/src/questionnaire/specifications/FabriqueDeSpecifications.ts
  anssi-nis2-ui/src/questionnaire/specifications/FormatDesSpecificationsCSV.ts
  anssi-nis2-ui/src/questionnaire/specifications/regles/RegleFournitureDeServicesNumerique.ts
  anssi-nis2-ui/src/questionnaire/specifications/specifications-completes.csv
  anssi-nis2-ui/test/questionnaire/specifications/FabriqueDeSpecifications.spec.ts
  anssi-nis2-ui/test/questionnaire/specifications/csv/specification-ose-est-regulee-ee.csv
  anssi-nis2-ui/test/questionnaire/specifications/csv/specification-une-ligne.csv
Labels: enhancement

#157 Ajout de la page Sécurité
  anssi-nis2-ui/src/App.scss
  anssi-nis2-ui/src/Components/PagesEdito/Securite.tsx
  anssi-nis2-ui/src/Components/PiedDePage.tsx
  anssi-nis2-ui/src/assets/encart-homologation/encartHomologation.desktop.png
  anssi-nis2-ui/src/assets/encart-homologation/encartHomologation.mobile.png
  anssi-nis2-ui/src/assets/encart-homologation/encartHomologation.tablette.png
  anssi-nis2-ui/src/router.tsx
Labels: enhancement

#161 Supprime la mention à la licence etalab
  anssi-nis2-ui/src/Components/PiedDePage.tsx
Labels: enhancement

#160 Mets à jour les mentions légales
  anssi-nis2-ui/src/Components/PagesEdito/MentionsLegales.tsx
Labels: enhancement

#159 Ajoute la page « Politique de confidentialité »
  anssi-nis2-ui/src/Components/FormRestezInformes.tsx
  anssi-nis2-ui/src/Components/PagesEdito/PolitiqueConfidentialite.tsx
  anssi-nis2-ui/src/Components/PiedDePage.tsx
  anssi-nis2-ui/src/router.tsx
Labels: enhancement

#158 [Éligibilité en CSV] Lecture d'un CSV de PROD
  anssi-nis2-ui/src/References/LibellesActivites.ts
  anssi-nis2-ui/src/References/LibellesSousSecteursActivite.ts
  anssi-nis2-ui/src/References/ListeDescriptionsActivites.ts
  anssi-nis2-ui/src/questionnaire/specifications/FabriqueDeSpecifications.ts
  anssi-nis2-ui/src/questionnaire/specifications/Specifications.ts
  anssi-nis2-ui/src/questionnaire/specifications/regles/RegleActivites.ts
  anssi-nis2-ui/src/questionnaire/specifications/regles/RegleEntiteOSE.ts
  anssi-nis2-ui/src/questionnaire/specifications/regles/RegleFournitureDeServicesNumerique.ts
  anssi-nis2-ui/src/questionnaire/specifications/regles/RegleLocalisation.ts
  anssi-nis2-ui/src/questionnaire/specifications/regles/RegleSecteurs.ts
  anssi-nis2-ui/src/questionnaire/specifications/regles/RegleSousSecteurs.ts
  anssi-nis2-ui/src/questionnaire/specifications/regles/RegleTaille.ts
  anssi-nis2-ui/src/questionnaire/specifications/regles/RegleTypeDeStructure.ts
  anssi-nis2-ui/src/questionnaire/specifications/specifications-completes.csv
  anssi-nis2-ui/src/stories/utilitaires/Simulateur.actions.ts
  anssi-nis2-ui/test/questionnaire/specifications/FabriqueDeSpecifications.spec.ts
  anssi-nis2-ui/test/questionnaire/specifications/LeTestDeLaSpecificationCompleteEnCsv.spec.ts
  anssi-nis2-ui/test/questionnaire/specifications/casDeTests.activites.ts
  anssi-nis2-ui/test/questionnaire/specifications/csv/specification-ose-est-regulee-ee.csv
  anssi-nis2-ui/test/questionnaire/specifications/csv/specification-une-ligne.csv
  anssi-nis2-ui/test/questionnaire/specifications/csv/specs-completes-de-travail.csv
Labels: enhancement

#162 Mets à jour le style du BOM
  anssi-nis2-ui/src/App.scss
  anssi-nis2-ui/src/Components/BOM/BOM.tsx
  anssi-nis2-ui/src/assets/entete-fenetre-bom.svg
  anssi-nis2-ui/src/assets/icone_aide_point_interrogation.svg
  anssi-nis2-ui/src/assets/vignette-bom.svg
Labels: enhancement

#163 Comparaison entre réponse v1 et v2
  anssi-nis2-ui/src/Components/Simulateur/AiguilleVersEtapeResultat.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeResultat.tsx
  anssi-nis2-ui/src/Components/Simulateur/compareEtEnvoieVersSentry.tsx
  anssi-nis2-ui/src/stories/Components/Simulateur/EtapesRefacto/EtapeResultat.stories.tsx
Labels: enhancement

#164 Utilise les specs CSV de travail pour la PROD
  anssi-nis2-ui/src/questionnaire/specifications/specifications-completes.csv
Labels: enhancement

#167 Change le matching de la règle `RegleFournitureDeServicesNumerique`
  anssi-nis2-ui/src/questionnaire/specifications/regles/RegleFournitureDeServicesNumerique.ts
  anssi-nis2-ui/test/questionnaire/specifications/FabriqueDeSpecifications.spec.ts
Labels: enhancement

#172 Supprime du code mort
  anssi-nis2-api/src/informations-emails/informations-emails.providers.ts
  anssi-nis2-api/src/simulateur-reponse/simulateur-reponse.providers.ts
  anssi-nis2-ui/src/Services/Echaffaudages/AssistantsEchaffaudages.tsx
  commun/core/src/Domain/Simulateur/Activite.predicats.ts
  commun/core/src/Domain/Simulateur/EtatEtape.predicats.ts
  commun/core/src/Domain/Simulateur/services/ChampSimulateur/ValidationReponses.ts
  commun/core/src/Domain/Simulateur/services/ChampSimulateur/champs.predicats.ts
  commun/core/src/Domain/Simulateur/services/DonneesFormulaire/DonneesFormulaire.predicats.ts
  commun/core/src/Domain/Simulateur/services/SecteurActivite/SecteurActivite.predicats.ts
  commun/core/src/Domain/Simulateur/services/SousSecteurActivite/SousSecteurActivite.operations.ts
  commun/core/test/Domaine/arbitraires/ValeursChampsSimulateur.arbitraire.ts
  commun/utils/services/string.operations.ts
Labels: enhancement

#173 Logue en INFO le cas du « Non régulée »
  anssi-nis2-ui/src/Components/Simulateur/compareEtEnvoieVersSentry.tsx
Labels: enhancement

#177 Corrige le titre Sentry
  anssi-nis2-ui/src/Components/Simulateur/compareEtEnvoieVersSentry.tsx
Labels: bug

#178 Retire « Administration publique » des secteurs
  anssi-nis2-ui/src/References/LibellesActivites.ts
  anssi-nis2-ui/src/References/LibellesSecteursActivite.ts
  anssi-nis2-ui/src/References/ListeDescriptionsActivites.ts
  commun/core/src/Domain/Simulateur/Activite.definitions.ts
  commun/core/src/Domain/Simulateur/Activite.operations.ts
  commun/core/src/Domain/Simulateur/Activite.valeurs.ts
  commun/core/src/Domain/Simulateur/SecteurActivite.valeurs.ts
Labels: Front
