Repository betagouv/anssi-nis2, pull requests merged in 2024-03, with the labels that each got.

#91 Ajoute la page d'informations détaillées sur la directive NIS 2
  anssi-nis2-ui/src/App.css
  anssi-nis2-ui/src/Components/Directive/CarteEnSavoirPlus.tsx
  anssi-nis2-ui/src/Components/Directive/CarteEntite.tsx
  anssi-nis2-ui/src/Components/Directive/CarteInformation.tsx
  anssi-nis2-ui/src/Components/Directive/ItemSecteurConcerne.tsx
  anssi-nis2-ui/src/Components/Directive/LienRubrique.tsx
  anssi-nis2-ui/src/Components/Directive/ListeSecteursConcernes.tsx
  anssi-nis2-ui/src/Components/Directive/SecteurActivite.tsx
  anssi-nis2-ui/src/Components/Directive/Sommaire.tsx
  anssi-nis2-ui/src/Components/MenuDesktop.tsx
  anssi-nis2-ui/src/Components/MenuMobile.tsx
  anssi-nis2-ui/src/Directive.tsx
  anssi-nis2-ui/src/assets/Directeur ANSSI.png
  anssi-nis2-ui/src/assets/administrations-publiques.svg
  anssi-nis2-ui/src/assets/collectivites-territoriales.svg
  anssi-nis2-ui/src/assets/demarche.svg
  anssi-nis2-ui/src/assets/directive-hero.svg
  anssi-nis2-ui/src/assets/en-savoir-plus/directive.svg
  anssi-nis2-ui/src/assets/en-savoir-plus/faq.svg
  anssi-nis2-ui/src/assets/en-savoir-plus/presentation.svg
  anssi-nis2-ui/src/assets/grandes-entreprises.svg
  anssi-nis2-ui/src/assets/icone-burger.svg
  anssi-nis2-ui/src/assets/icone-fermer.svg
  anssi-nis2-ui/src/assets/icone-fleche-bas.svg
  anssi-nis2-ui/src/assets/icone-fleche-haut.svg
  anssi-nis2-ui/src/assets/icone-menu.svg
  anssi-nis2-ui/src/assets/moyennes-entreprises.svg
  anssi-nis2-ui/src/assets/secteurs-concernes/administrations-publiques.svg
  anssi-nis2-ui/src/assets/secteurs-concernes/alimentaires.svg
  anssi-nis2-ui/src/assets/secteurs-concernes/bancaire.svg
  anssi-nis2-ui/src/assets/secteurs-concernes/communication.svg
  anssi-nis2-ui/src/assets/secteurs-concernes/dechets.svg
  anssi-nis2-ui/src/assets/secteurs-concernes/eaux-potables.svg
  anssi-nis2-ui/src/assets/secteurs-concernes/eaux-usees.svg
  anssi-nis2-ui/src/assets/secteurs-concernes/energies.svg
  anssi-nis2-ui/src/assets/secteurs-concernes/espace.svg
  anssi-nis2-ui/src/assets/secteurs-concernes/financiers.svg
  anssi-nis2-ui/src/assets/secteurs-concernes/fournisseur-numerique.svg
  anssi-nis2-ui/src/assets/secteurs-concernes/infrastructures.svg
  anssi-nis2-ui/src/assets/secteurs-concernes/manufacture.svg
  anssi-nis2-ui/src/assets/secteurs-concernes/postaux.svg
  anssi-nis2-ui/src/assets/secteurs-concernes/produits-chimiques.svg
  anssi-nis2-ui/src/assets/secteurs-concernes/recherche.svg
  anssi-nis2-ui/src/assets/secteurs-concernes/sante.svg
  anssi-nis2-ui/src/assets/secteurs-concernes/transport.svg
  anssi-nis2-ui/src/directive.css
  anssi-nis2-ui/src/directive.desktop.css
  anssi-nis2-ui/src/directive.tablette.css
  anssi-nis2-ui/src/router.tsx
Labels: enhancement

#92 Feat/ajout du bom
  anssi-nis2-ui/.env.template
  anssi-nis2-ui/src/App.scss
  anssi-nis2-ui/src/Components/BOM/BOM.tsx
  anssi-nis2-ui/src/Components/MiseEnPage.tsx
  anssi-nis2-ui/src/assets/entete-fenetre-bom.svg
  anssi-nis2-ui/src/assets/forme-chevron-blanc.svg
  anssi-nis2-ui/src/assets/vignette-bom.svg
Labels: enhancement, Front

#96 Modification de la home
  anssi-nis2-ui/src/Accueil.tsx
  anssi-nis2-ui/src/App.scss
  anssi-nis2-ui/src/Components/Accueil/BandeauAccueil.tsx
  anssi-nis2-ui/src/Components/Accueil/BandeauConcerne.tsx
  anssi-nis2-ui/src/Components/Accueil/BandeauInformationRS.tsx
  anssi-nis2-ui/src/Components/Accueil/BandeauQuandSePreparer.tsx
  anssi-nis2-ui/src/Components/Accueil/BandeauQuiEstANSSI.tsx
  anssi-nis2-ui/src/Components/Accueil/BandeauSePreprarer.tsx
  anssi-nis2-ui/src/Components/Accueil/CarteSePreparer.tsx
  anssi-nis2-ui/src/Components/Accueil/JalonEtape.tsx
  anssi-nis2-ui/src/Components/Accueil/Paragraphe.tsx
  anssi-nis2-ui/src/Components/BlocPrincipal.tsx
  anssi-nis2-ui/src/Components/Directive/LienRubrique.tsx
  anssi-nis2-ui/src/Components/Directive/Sommaire.tsx
  anssi-nis2-ui/src/Components/PiedDePage.tsx
  anssi-nis2-ui/src/Components/ReseauxSociaux.tsx
  anssi-nis2-ui/src/Directive.tsx
  anssi-nis2-ui/src/accueil.desktop.scss
  anssi-nis2-ui/src/accueil.petit-desktop.scss
  anssi-nis2-ui/src/accueil.scss
  anssi-nis2-ui/src/accueil.tablette.scss
  anssi-nis2-ui/src/assets/chemin-etape.svg
  anssi-nis2-ui/src/assets/chemin-gauche.svg
  anssi-nis2-ui/src/assets/home-assujeti.svg
  anssi-nis2-ui/src/assets/home-declarer.svg
  anssi-nis2-ui/src/assets/home-directive.svg
  anssi-nis2-ui/src/assets/marches-tablette.svg
  anssi-nis2-ui/src/assets/marches.svg
  anssi-nis2-ui/src/directive.desktop.scss
  anssi-nis2-ui/src/directive.scss
  anssi-nis2-ui/src/directive.tablette.scss
  package-lock.json
  package.json
Labels: enhancement

#97 [Correction] Z-index du bom
  anssi-nis2-ui/src/App.scss
Labels: bug

#99 feat: ajout module filtrage ip
  anssi-nis2-api/.env.template
  anssi-nis2-api/package.json
  anssi-nis2-api/src/app.module.ts
  anssi-nis2-api/src/intergiciels/serveur-statique-configurable/chargeur-express-basic.auth.ts
  anssi-nis2-api/src/optionsFiltrageIp.ts
  anssi-nis2-api/src/test/intergiciels/express-basic-auth.loader.spec.ts
  package-lock.json
Labels: enhancement

#102 Ajout du format responsif du simulateur
  anssi-nis2-ui/src/App.scss
  anssi-nis2-ui/src/Components/AidezNousAmeliorerService.tsx
  anssi-nis2-ui/src/Components/FormRestezInformes.tsx
  anssi-nis2-ui/src/Components/Simulateur/BandeauConcerneSimulateur.tsx
  anssi-nis2-ui/src/Components/Simulateur/Resultats/LigneEtMaintenant.tsx
  anssi-nis2-ui/src/Components/Simulateur/SimulateurEtapeForm.tsx
  anssi-nis2-ui/src/Components/Simulateur/SimulateurEtapePrealable.tsx
  anssi-nis2-ui/src/Components/Simulateur/StepperNavigation.tsx
  anssi-nis2-ui/src/Simulateur.tsx
  anssi-nis2-ui/src/assets/icone-info.svg
  anssi-nis2-ui/src/directive.scss
  anssi-nis2-ui/src/simulateur.petit-desktop.scss
  anssi-nis2-ui/src/simulateur.scss
Labels: enhancement

#103 [INFRA] Filtrage IP à un seul endroit
  anssi-nis2-api/.env.template
  anssi-nis2-api/package.json
  anssi-nis2-api/src/app.module.ts
  anssi-nis2-api/src/intergiciels/serveur-statique-configurable/chargeur-express-basic.auth.ts
  anssi-nis2-api/src/main.ts
  anssi-nis2-api/src/optionsFiltrageIp.ts
  package-lock.json
Labels: documentation

#105 Correction d'une typo
  .husky/pre-commit
  anssi-nis2-ui/src/Components/PiedDePage.tsx
  anssi-nis2-ui/src/router.tsx
  anssi-nis2-ui/src/stories/Pages/PagesEditos.stories.tsx
Labels: bug

#109 Fix/erreur appel api email
  anssi-nis2-api/.env.template
  anssi-nis2-api/src/informations-emails/informations-emails.service.ts
  anssi-nis2-api/src/main.ts
  anssi-nis2-ui/index.html
  anssi-nis2-ui/src/Services/sendFormDataToApi.ts
Labels: bug, Front
