Repository betagouv/anssi-nis2, pull requests merged in 2024-04, with the labels that each got.

#108 Changement d'architecture pour le questionnaire
  anssi-nis2-ui/.env.template
  anssi-nis2-ui/src/Components/Simulateur/ChargeurEtape.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeAppartenanceUE.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeDesignation.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapePrealable.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeSecteursActivite.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeSousSecteursActivite.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeTailleEntitePrivee.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeTypeStructure.tsx
  anssi-nis2-ui/src/Components/Simulateur/Questionnaire.tsx
  anssi-nis2-ui/src/questionnaire/actions.ts
  anssi-nis2-ui/src/questionnaire/reducerQuestionnaire.ts
  anssi-nis2-ui/test/questionnaire/reducerQuestionnaire.spec.ts
Labels: Front

#111 Ajout de l'étape "Résultat"
  anssi-nis2-ui/.env.template
  anssi-nis2-ui/src/Components/Simulateur/ChargeurEtape.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeResultat.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeSousSecteursActivite.tsx
  anssi-nis2-ui/src/Components/Simulateur/Questionnaire.tsx
  anssi-nis2-ui/src/questionnaire/reducerQuestionnaire.ts
Labels: enhancement

#114 Fix: affiche activité même si sous-secteur autre est coché
  anssi-nis2-ui/src/Components/Simulateur/Etapes/EtapesQuestionnaire.ts
  commun/core/src/Domain/Simulateur/Activite.operations.ts
  commun/core/src/Domain/Simulateur/services/SousSecteurActivite/SousSecteurActivite.operations.ts
Labels: bug, Front

#115 Ajout de l'étape « Activités pratiquées »
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeActivites.tsx
  anssi-nis2-ui/src/Components/Simulateur/Questionnaire.tsx
  anssi-nis2-ui/src/questionnaire/actions.ts
  anssi-nis2-ui/src/questionnaire/reducerQuestionnaire.ts
  anssi-nis2-ui/src/questionnaire/selecteursQuestionnaire.ts
  anssi-nis2-ui/test/questionnaire/reducerQuestionnaire.spec.ts
  anssi-nis2-ui/test/questionnaire/selecteursQuestionnaire.spec.ts
  commun/core/src/Domain/Simulateur/SousSecteurActivite.operations.ts
  commun/core/src/Domain/Simulateur/services/SousSecteurActivite/SousSecteurActivite.operations.ts
  commun/core/test/Domaine/Simulateur/services/SousSecteurActivite/SousSecteurActivite.operations.spec.ts
Labels: enhancement

#117 Empêche « Suivant » tant que la réponse est incomplète
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeLocalisationEtablissementPrincipal.tsx
Labels: enhancement

#118 Ajout de l'étape « Localisation de votre activité » pour les services numériques
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeLocalisationServicesNumeriques.tsx
  anssi-nis2-ui/src/Components/Simulateur/Questionnaire.tsx
  anssi-nis2-ui/src/questionnaire/actions.ts
  anssi-nis2-ui/src/questionnaire/reducerQuestionnaire.ts
  anssi-nis2-ui/test/questionnaire/reducerQuestionnaire.spec.ts
Labels: enhancement

#119 Ajoute la prise en charge du bouton « Précédent »
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeActivites.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeAppartenanceUE.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeDesignation.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeLocalisationEtablissementPrincipal.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeLocalisationServicesNumeriques.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeSecteursActivite.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeSousSecteursActivite.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeTailleEntitePrivee.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeTypeStructure.tsx
  anssi-nis2-ui/src/Components/Simulateur/PrecedentSuivant.tsx
  anssi-nis2-ui/src/Components/Simulateur/Questionnaire.tsx
  anssi-nis2-ui/src/questionnaire/quiSupporteUndo.ts
  anssi-nis2-ui/test/questionnaire/reducerUndo.spec.ts
Labels: enhancement

#124 Évite les boucles infinies dans le questionnaire refacto
  anssi-nis2-ui/src/questionnaire/reducerQuestionnaire.ts
  anssi-nis2-ui/test/questionnaire/reducerQuestionnaire.spec.ts
Labels: bug

#126 Titre de page avec le questionnaire v2
  anssi-nis2-ui/src/Components/Simulateur/ChargeurEtape.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeActivites.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeAppartenanceUE.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeDesignation.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeLocalisationEtablissementPrincipal.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeLocalisationServicesNumeriques.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapePrealable.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeSecteursActivite.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeSousSecteursActivite.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeTailleEntitePrivee.tsx
  anssi-nis2-ui/src/Components/Simulateur/EtapesRefacto/EtapeTypeStructure.tsx
  anssi-nis2-ui/src/Components/Simulateur/Questionnaire.tsx
  anssi-nis2-ui/src/Components/Simulateur/TitresEtapes.ts
Labels: enhancement

#127 Réparation du scroll vers le haut du formulaire
  anssi-nis2-ui/src/Components/Simulateur/PrecedentSuivant.tsx
  anssi-nis2-ui/src/Components/Simulateur/Questionnaire.tsx
  anssi-nis2-ui/src/Components/Simulateur/scroll.ts
Labels: bug

#128 Changements divers sur les appels API
  anssi-nis2-api/.env.template
  anssi-nis2-ui/src/Components/Simulateur/PrecedentSuivant.tsx
  anssi-nis2-ui/src/Services/Simulateur/Operations/appelsApi.d.ts
  anssi-nis2-ui/src/Services/prepare.ts
  anssi-nis2-ui/src/Services/sendFormDataToApi.ts
  anssi-nis2-ui/src/stories/Components/Simulateur/EtapesRefacto/EtapeResultat.stories.tsx
  anssi-nis2-ui/src/stories/utilitaires/PageDecorator.tsx
  anssi-nis2-ui/src/stories/utilitaires/mocks.ts
Labels: enhancement

#129 Ajoute lien « Nous contacter » dans le BOM
  anssi-nis2-ui/src/Components/BOM/BOM.tsx
Labels: enhancement

#130 Branchement de l'inscription utilisateur à l'API Brevo
  anssi-nis2-api/.env.template
  anssi-nis2-api/package.json
  anssi-nis2-api/src/app.module.ts
  anssi-nis2-api/src/informations-emails/crm.InMemory.ts
  anssi-nis2-api/src/informations-emails/crm.brevo.ts
  anssi-nis2-api/src/informations-emails/crm.ts
  anssi-nis2-api/src/informations-emails/informations-emails.controller.ts
  anssi-nis2-api/src/informations-emails/informations-emails.module.ts
  anssi-nis2-api/src/informations-emails/informations-emails.service.spec.ts
  anssi-nis2-api/src/informations-emails/informations-emails.service.ts
  package-lock.json
Labels: enhancement

#133 Nouveaux composants pour le résultat du test
  .github/workflows/node.js.yml
  anssi-nis2-ui/src/Components/Simulateur/Resultats/PointsAttention.contenus.tsx
  anssi-nis2-ui/src/Components/Simulateur/Resultats/PointsAttention.tsx
  anssi-nis2-ui/src/Components/Simulateur/Resultats/TamponResultat.tsx
  anssi-nis2-ui/src/stories/Components/Simulateur/Resultat/PointsAttention.stories.tsx
  anssi-nis2-ui/src/stories/Components/Simulateur/Resultat/TamponResultat.stories.tsx
  commun/core/src/Domain/Simulateur/Regulation.definitions.ts
Labels: enhancement
